/*
 * This file is generated by jOOQ.
*/
package procul.studios.sqlbindings.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import procul.studios.sqlbindings.tables.Usertable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsertableRecord extends UpdatableRecordImpl<UsertableRecord> implements Record10<Integer, String, String, Long, Long, Integer, Integer, byte[], byte[], byte[]> {

    private static final long serialVersionUID = -1738315967;

    /**
     * Setter for <code>usertable.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>usertable.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>usertable.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>usertable.USERNAME</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>usertable.PASSWORDHASH</code>.
     */
    public void setPasswordhash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>usertable.PASSWORDHASH</code>.
     */
    public String getPasswordhash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>usertable.CURRENCY</code>.
     */
    public void setCurrency(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>usertable.CURRENCY</code>.
     */
    public Long getCurrency() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>usertable.LASTLOGIN</code>.
     */
    public void setLastlogin(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>usertable.LASTLOGIN</code>.
     */
    public Long getLastlogin() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>usertable.USERTYPEFIELD</code>.
     */
    public void setUsertypefield(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>usertable.USERTYPEFIELD</code>.
     */
    public Integer getUsertypefield() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>usertable.XP</code>.
     */
    public void setXp(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>usertable.XP</code>.
     */
    public Integer getXp() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>usertable.INVENTORY</code>.
     */
    public void setInventory(byte... value) {
        set(7, value);
    }

    /**
     * Getter for <code>usertable.INVENTORY</code>.
     */
    public byte[] getInventory() {
        return (byte[]) get(7);
    }

    /**
     * Setter for <code>usertable.ROBOTS</code>.
     */
    public void setRobots(byte... value) {
        set(8, value);
    }

    /**
     * Getter for <code>usertable.ROBOTS</code>.
     */
    public byte[] getRobots() {
        return (byte[]) get(8);
    }

    /**
     * Setter for <code>usertable.AVATAR</code>.
     */
    public void setAvatar(byte... value) {
        set(9, value);
    }

    /**
     * Getter for <code>usertable.AVATAR</code>.
     */
    public byte[] getAvatar() {
        return (byte[]) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Long, Long, Integer, Integer, byte[], byte[], byte[]> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Long, Long, Integer, Integer, byte[], byte[], byte[]> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usertable.USERTABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Usertable.USERTABLE.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Usertable.USERTABLE.PASSWORDHASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Usertable.USERTABLE.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Usertable.USERTABLE.LASTLOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Usertable.USERTABLE.USERTYPEFIELD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Usertable.USERTABLE.XP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field8() {
        return Usertable.USERTABLE.INVENTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field9() {
        return Usertable.USERTABLE.ROBOTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field10() {
        return Usertable.USERTABLE.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPasswordhash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getLastlogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUsertypefield();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getXp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component8() {
        return getInventory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component9() {
        return getRobots();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component10() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPasswordhash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getLastlogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUsertypefield();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getXp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value8() {
        return getInventory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value9() {
        return getRobots();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value10() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value3(String value) {
        setPasswordhash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value4(Long value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value5(Long value) {
        setLastlogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value6(Integer value) {
        setUsertypefield(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value7(Integer value) {
        setXp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value8(byte... value) {
        setInventory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value9(byte... value) {
        setRobots(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord value10(byte... value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsertableRecord values(Integer value1, String value2, String value3, Long value4, Long value5, Integer value6, Integer value7, byte[] value8, byte[] value9, byte[] value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsertableRecord
     */
    public UsertableRecord() {
        super(Usertable.USERTABLE);
    }

    /**
     * Create a detached, initialised UsertableRecord
     */
    public UsertableRecord(Integer id, String username, String passwordhash, Long currency, Long lastlogin, Integer usertypefield, Integer xp, byte[] inventory, byte[] robots, byte[] avatar) {
        super(Usertable.USERTABLE);

        set(0, id);
        set(1, username);
        set(2, passwordhash);
        set(3, currency);
        set(4, lastlogin);
        set(5, usertypefield);
        set(6, xp);
        set(7, inventory);
        set(8, robots);
        set(9, avatar);
    }
}
