/*
 * This file is generated by jOOQ.
*/
package procul.studios.sqlbindings;


import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import procul.studios.sqlbindings.tables.Authtable;
import procul.studios.sqlbindings.tables.Usertable;
import procul.studios.sqlbindings.tables.records.AuthtableRecord;
import procul.studios.sqlbindings.tables.records.UsertableRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthtableRecord> PK_AUTHTABLE = UniqueKeys0.PK_AUTHTABLE;
    public static final UniqueKey<UsertableRecord> PK_USERTABLE = UniqueKeys0.PK_USERTABLE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AuthtableRecord> PK_AUTHTABLE = createUniqueKey(Authtable.AUTHTABLE, "pk_authtable", Authtable.AUTHTABLE.ID);
        public static final UniqueKey<UsertableRecord> PK_USERTABLE = createUniqueKey(Usertable.USERTABLE, "pk_usertable", Usertable.USERTABLE.ID);
    }
}
