/*
 * This file is generated by jOOQ.
*/
package procul.studios.sqlbindings;

import javax.annotation.Generated;

import procul.studios.sqlbindings.tables.Authtable;
import procul.studios.sqlbindings.tables.Usertable;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>authtable</code>.
     */
    public static final Authtable AUTHTABLE = procul.studios.sqlbindings.tables.Authtable.AUTHTABLE;

    /**
     * The table <code>usertable</code>.
     */
    public static final Usertable USERTABLE = procul.studios.sqlbindings.tables.Usertable.USERTABLE;
}
