/*
 * This file is generated by jOOQ.
*/
package procul.studios.sqlbindings;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import procul.studios.sqlbindings.tables.Authtable;
import procul.studios.sqlbindings.tables.Usertable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -371472175;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>authtable</code>.
     */
    public final Authtable AUTHTABLE = procul.studios.sqlbindings.tables.Authtable.AUTHTABLE;

    /**
     * The table <code>usertable</code>.
     */
    public final Usertable USERTABLE = procul.studios.sqlbindings.tables.Usertable.USERTABLE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Authtable.AUTHTABLE,
            Usertable.USERTABLE);
    }
}
