/*
 * This file is generated by jOOQ.
*/
package procul.studios.sqlbindings;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;

import procul.studios.sqlbindings.tables.Authtable;
import procul.studios.sqlbindings.tables.Usertable;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_AUTHTABLE_1 = Indexes0.SQLITE_AUTOINDEX_AUTHTABLE_1;
    public static final Index SQLITE_AUTOINDEX_AUTHTABLE_2 = Indexes0.SQLITE_AUTOINDEX_AUTHTABLE_2;
    public static final Index SQLITE_AUTOINDEX_USERTABLE_1 = Indexes0.SQLITE_AUTOINDEX_USERTABLE_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index SQLITE_AUTOINDEX_AUTHTABLE_1 = createIndex("sqlite_autoindex_authtable_1", Authtable.AUTHTABLE, new OrderField[] { Authtable.AUTHTABLE.TOKEN }, true);
        public static Index SQLITE_AUTOINDEX_AUTHTABLE_2 = createIndex("sqlite_autoindex_authtable_2", Authtable.AUTHTABLE, new OrderField[] { Authtable.AUTHTABLE.USERID }, true);
        public static Index SQLITE_AUTOINDEX_USERTABLE_1 = createIndex("sqlite_autoindex_usertable_1", Usertable.USERTABLE, new OrderField[] { Usertable.USERTABLE.USERNAME }, true);
    }
}
